# Offer the fix lint bot command
offerLintFix:
  # Which job name to look for
  jobName: lint
  # Define which linter outputs should be checked for auto-fixability
  linters:
    - eslint
    - wotan
    - prettier

# Check whether the resulting squash-commit will be semantic
semanticSquash: true
